version: '3.3'
services:
  nodejs-ts-docker:
    container_name: nodejs-ts-docker
    restart: always
    image: fazjaune/nodejs-typescript-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=3000
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/app